server:
  port: ${PORT:7030}

spring:
  application:
    name: event-consumer
  profiles:
    default: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
  output:
    ansi:
      enabled: always

app:
  kafka:
    topics:
      log-events: ${KAFKA_TOPIC_LOG_EVENTS:mvp.log-events}
  opensearch:
    url: ${OPENSEARCH_URL:http://localhost:19200}
    index-name: ${OPENSEARCH_INDEX_NAME:logs-write}
    pipeline-name: ${OPENSEARCH_PIPELINE_NAME:logs-pipeline}
