server:
  port: ${PORT:7020}

spring:
  application:
    name: log-service
  profiles:
    default: local
  jackson:
    serialization:
      write-dates-as-timestamps: false
  output:
    ansi:
      enabled: always

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%-5level) %clr([%thread]){faint} %clr(trace_id=%X{trace_id:-}){cyan} %clr(request_id=%X{request_id:-}){cyan} %clr(%logger{36}){blue} - %msg%n"

app:
  kafka:
    topics:
      log-events: ${KAFKA_TOPIC_LOG_EVENTS:mvp.log-events}
  opensearch:
    url: ${OPENSEARCH_URL:http://localhost:19200}
    read-target: ${OPENSEARCH_READ_TARGET:logs-read}
